version: "3.8"

services:
  mysql:
    image: mysql
    container_name: innovai-mysql-container
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # env_file:
    #   - .env
    ports:
      - "3307:3306"
